// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for About Page documents */
interface AboutPageDocumentData {
    /**
     * Main Text field in *About Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_page.main_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    main_text: prismicT.KeyTextField;
}
/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AboutPageDocumentData>, "about_page", Lang>;
/** Content for Artist documents */
interface ArtistDocumentData {
    /**
     * Artist Name field in *Artist*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.artist_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    artist_name: prismicT.KeyTextField;
    /**
     * Artist Link field in *Artist*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.artist_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    artist_link: prismicT.LinkField;
    /**
     * Additional Information field in *Artist*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: artist.additional_information
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    additional_information: prismicT.RichTextField;
}
/**
 * Artist document from Prismic
 *
 * - **API ID**: `artist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ArtistDocumentData>, "artist", Lang>;
/** Content for Contact Page documents */
interface ContactPageDocumentData {
    /**
     * Slice Zone field in *Contact Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ContactPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Contact Page → Slice Zone*
 *
 */
type ContactPageDocumentDataSlicesSlice = never;
/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContactPageDocumentData>, "contact_page", Lang>;
/** Content for Exhibition documents */
interface ExhibitionDocumentData {
    /**
     * Title field in *Exhibition*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exhibition.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Start Date field in *Exhibition*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: exhibition.start_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    start_date: prismicT.DateField;
    /**
     * End Date field in *Exhibition*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: exhibition.end_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    end_date: prismicT.DateField;
    /**
     * Slice Zone field in *Exhibition*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: exhibition.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ExhibitionDocumentDataSlicesSlice>;
}
/**
 * Slice for *Exhibition → Slice Zone*
 *
 */
type ExhibitionDocumentDataSlicesSlice = never;
/**
 * Exhibition document from Prismic
 *
 * - **API ID**: `exhibition`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExhibitionDocumentData>, "exhibition", Lang>;
/** Content for Exhibitions Page documents */
interface ExhibitionsPageDocumentData {
    /**
     * Slice Zone field in *Exhibitions Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: exhibitions_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ExhibitionsPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Exhibitions Page → Slice Zone*
 *
 */
type ExhibitionsPageDocumentDataSlicesSlice = MainMenuSlice;
/**
 * Exhibitions Page document from Prismic
 *
 * - **API ID**: `exhibitions_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExhibitionsPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExhibitionsPageDocumentData>, "exhibitions_page", Lang>;
/** Content for News documents */
interface NewsDocumentData {
    /**
     * Title field in *News*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Thumbnail field in *News*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: news.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * Content field in *News*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NewsDocumentData>, "news", Lang>;
export type AllDocumentTypes = AboutPageDocument | ArtistDocument | ContactPageDocument | ExhibitionDocument | ExhibitionsPageDocument | NewsDocument;
/**
 * Primary content in ExhibitionSlice → Primary
 *
 */
interface ExhibitionSliceSliceDefaultPrimary {
    /**
     * Title field in *ExhibitionSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: exhibition_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ExhibitionSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: exhibition_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for ExhibitionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ExhibitionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExhibitionSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ExhibitionSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ExhibitionSlice*
 *
 */
type ExhibitionSliceSliceVariation = ExhibitionSliceSliceDefault;
/**
 * ExhibitionSlice Shared Slice
 *
 * - **API ID**: `exhibition_slice`
 * - **Description**: `ExhibitionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExhibitionSliceSlice = prismicT.SharedSlice<"exhibition_slice", ExhibitionSliceSliceVariation>;
/**
 * Item in MainMenu → Items
 *
 */
export interface MainMenuSliceDefaultItem {
    /**
     * Menu Item field in *MainMenu → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_menu.items[].menu_item
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    menu_item: prismicT.KeyTextField;
    /**
     * Page field in *MainMenu → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: main_menu.items[].page
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    page: prismicT.RelationField;
}
/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MainMenu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainMenuSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<MainMenuSliceDefaultItem>>;
/**
 * Slice variation for *MainMenu*
 *
 */
type MainMenuSliceVariation = MainMenuSliceDefault;
/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_menu`
 * - **Description**: `MainMenu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainMenuSlice = prismicT.SharedSlice<"main_menu", MainMenuSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutPageDocumentData, AboutPageDocument, ArtistDocumentData, ArtistDocument, ContactPageDocumentData, ContactPageDocumentDataSlicesSlice, ContactPageDocument, ExhibitionDocumentData, ExhibitionDocumentDataSlicesSlice, ExhibitionDocument, ExhibitionsPageDocumentData, ExhibitionsPageDocumentDataSlicesSlice, ExhibitionsPageDocument, NewsDocumentData, NewsDocument, AllDocumentTypes, ExhibitionSliceSliceDefaultPrimary, ExhibitionSliceSliceDefault, ExhibitionSliceSliceVariation, ExhibitionSliceSlice, MainMenuSliceDefaultItem, MainMenuSliceDefault, MainMenuSliceVariation, MainMenuSlice };
    }
}
