// Code generated by Slice Machine. DO NOT EDIT.

import Artist from './Artist';
import ContactItem from './ContactItem';
import DefaultText from './DefaultText';
import ExhibitionContent from './ExhibitionContent';
import ExhibitionSlice from './ExhibitionSlice';
import MenuItem from './MenuItem';
import NewsItem from './NewsItem';

export {
	Artist,
	ContactItem,
	DefaultText,
	ExhibitionContent,
	ExhibitionSlice,
	MenuItem,
	NewsItem,
};

export const components = {
	artist: Artist,
	contact_item: ContactItem,
	default_text: DefaultText,
	exhibition_image: ExhibitionContent,
	exhibition_slice: ExhibitionSlice,
	menu_item: MenuItem,
	news_item: NewsItem,
};
