// Code generated by Slice Machine. DO NOT EDIT.

import Artist from './Artist';
import ContactItem from './ContactItem';
import DefaultText from './DefaultText';
import ExhibitionImage from './ExhibitionImage';
import ExhibitionSlice from './ExhibitionSlice';
import MainMenu from './MainMenu';
import NewsItem from './NewsItem';

export {
	Artist,
	ContactItem,
	DefaultText,
	ExhibitionImage,
	ExhibitionSlice,
	MainMenu,
	NewsItem,
};

export const components = {
	artist: Artist,
	contact_item: ContactItem,
	default_text: DefaultText,
	exhibition_image: ExhibitionImage,
	exhibition_slice: ExhibitionSlice,
	main_menu: MainMenu,
	news_item: NewsItem,
};
