// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  artist: dynamic(() => import("./Artist")),
  contact_item: dynamic(() => import("./ContactItem")),
  default_text: dynamic(() => import("./DefaultText")),
  exhibition_image: dynamic(() => import("./StandardContentItem")),
  exhibition_slice: dynamic(() => import("./ExhibitionSlice")),
  hero_slice: dynamic(() => import("./TitleSectionSlice")),
  menu_item: dynamic(() => import("./MenuItem")),
  news_item: dynamic(() => import("./NewsItem")),
};
