import Head from 'next/head'
import React from 'react'

const LayoutComponent = ({ children, header = null }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { header && 
        <header>
          { header }
        </header>
      }
      <main>
        { children }
      </main>
    </>
  )
}

export default LayoutComponent